(function () {
  window.LL_POPUP_CONFIG = {
  "testId": "blog-optin-v1",
  "webhookUrl": "https://script.google.com/macros/s/AKfycbzZmjBOkq6JYxFEeMzemDozYiUOuAYZjkBAw5-0afFO_JLb1-riB9jeAIfWn40nlDqVnQ/exec",
  "kajabiFormEmbed": "<script src=https://www.longevitylifestyle.me/forms/2148823405/embed.js></script>",
  "cooldownDaysAfterClose": 7,
  "cooldownDaysAfterSubmitAttempt": 90,
  "assignmentDays": 30,
  "triggers": {
    "delayMs": 20000,
    "scrollDepth": 0
  },
  "variants": [
    {
      "id": "A",
      "name": "Control",
      "active": true,
      "trafficSplit": 50,
      "headline": "Get Your Exact Daily Protein Target + Custom 7-Day Family Meal Plan (Free Grocery List Included)",
      "subheadline": "Takes 30 seconds. Backed by 1,000+ hours of Nutrition & Wellness Coaching. Built for busy parents.",
      "imageUrl": "https://res.cloudinary.com/dsvlnioq9/image/upload/v1782244453/protein_plan_app_mockup_cjshem.png",
      "width": 800,
      "backgroundColor": "#ffffff",
      "textColor": "#172026",
      "accentColor": "#06b00b",
      "buttonText": "Show My Protein Plan",
      "fontFamily": "Arial, Helvetica, sans-serif",
      "imageAlt": "",
      "textAlign": "center",
      "height": 560,
      "sizeToImage": true,
      "subheadlineHtml": "Takes 30 seconds. <b>Backed by 1,000+ hours of Nutrition &amp; Wellness Coaching. </b>Built for busy parents.",
      "proteinQuiz": {
        "targetWeightLabel": "Target weight in lbs",
        "targetWeightPlaceholder": "155",
        "strengthDaysLabel": "Strength training days per week",
        "strengthDaysPlaceholder": "Select days",
        "ageLabel": "Age",
        "agePlaceholder": "48",
        "progressEnabled": true,
        "progressStepOneLabel": "Step 1 of 2: Quick Calculator",
        "progressStepOneText": "Answer 3 quick questions to calculate your personalized protein target immediately.",
        "progressStepTwoLabel": "Step 2 of 2: Send Your Plan",
        "progressStepTwoText": "Your custom plan is almost ready.",
        "targetPreviewStyle": "inline",
        "targetPreviewLabel": "Your Daily Target:",
        "quizButtonText": "Calculate",
        "leadHeadline": "Your Personalized Protein Plan Is Almost Ready",
        "leadSubheadline": "Just enter your name and email below. We'll send you access to your 7-day meal plan + grocery list instantly, then you’ll have 100% control to customize it with your dietary preferences on the next page.",
        "firstNameLabel": "First name",
        "firstNamePlaceholder": "First Name",
        "emailLabel": "Email",
        "emailPlaceholder": "Email",
        "leadButtonText": "Send My Free Personalized Protein Plan Now",
        "backButtonText": "Back"
      },
      "trackingVersion": "6/23/2026",
      "trackingFingerprint": "{\"headline\":\"Get Your Exact Daily Protein Target + Custom 7-Day Family Meal Plan (Free Grocery List Included)\",\"subheadline\":\"Takes 30 seconds. Backed by 1,000+ hours of Nutrition & Wellness Coaching. Built for busy parents.\",\"subheadlineHtml\":\"Takes 30 seconds. <b>Backed by 1,000+ hours of Nutrition &amp; Wellness Coaching. </b>Built for busy parents.\",\"buttonText\":\"Show My Protein Plan\",\"imageUrl\":\"https://res.cloudinary.com/dsvlnioq9/image/upload/v1782244453/protein_plan_app_mockup_cjshem.png\",\"imageAlt\":\"\",\"width\":800,\"height\":560,\"sizeToImage\":true,\"backgroundColor\":\"#ffffff\",\"textColor\":\"#172026\",\"accentColor\":\"#06b00b\",\"fontFamily\":\"Arial, Helvetica, sans-serif\",\"textAlign\":\"center\",\"trafficSplit\":50,\"proteinQuiz\":{\"targetWeightLabel\":\"Target weight in lbs\",\"targetWeightPlaceholder\":\"155\",\"strengthDaysLabel\":\"Strength training days per week\",\"strengthDaysPlaceholder\":\"Select days\",\"ageLabel\":\"Age\",\"agePlaceholder\":\"48\",\"progressEnabled\":true,\"progressStepOneLabel\":\"Step 1 of 2: Quick Calculator\",\"progressStepOneText\":\"Answer 3 quick questions to calculate your personalized protein target immediately.\",\"progressStepTwoLabel\":\"Step 2 of 2: Send Your Plan\",\"progressStepTwoText\":\"Your custom plan is almost ready.\",\"targetPreviewStyle\":\"inline\",\"targetPreviewLabel\":\"Your Daily Target:\",\"quizButtonText\":\"Calculate\",\"leadHeadline\":\"Your Personalized Protein Plan Is Almost Ready\",\"leadSubheadline\":\"Just enter your name and email below. We'll send you access to your 7-day meal plan + grocery list instantly, then you’ll have 100% control to customize it with your dietary preferences on the next page.\",\"firstNameLabel\":\"First name\",\"firstNamePlaceholder\":\"First Name\",\"emailLabel\":\"Email\",\"emailPlaceholder\":\"Email\",\"leadButtonText\":\"Send My Free Personalized Protein Plan Now\",\"backButtonText\":\"Back\"}}"
    },
    {
      "id": "B",
      "name": "Benefit Led",
      "active": true,
      "trafficSplit": 50,
      "headline": "Get Your Exact Daily Protein Target + Custom 7-Day Family Meal Plan (Free Grocery List Included)",
      "subheadline": "Takes 30 seconds. Backed by 1,000+ hours of Nutrition & Wellness Coaching. Built for busy parents. ",
      "imageUrl": "https://res.cloudinary.com/dsvlnioq9/image/upload/v1782135119/protien_plan_calculate_preview_and_male_female_pomke9.png",
      "width": 560,
      "backgroundColor": "#fbfaf7",
      "textColor": "#1c2520",
      "accentColor": "#06b00b",
      "buttonText": "Show My Protein Plan",
      "fontFamily": "Arial, Helvetica, sans-serif",
      "imageAlt": "",
      "textAlign": "center",
      "height": 560,
      "sizeToImage": true,
      "subheadlineHtml": "<span><span>Takes 30 seconds. <b>Backed by 1,000+ hours of Nutrition &amp; Wellness Coaching. </b></span></span><span>Built for busy parents. </span>",
      "proteinQuiz": {
        "targetWeightLabel": "Target weight in lbs",
        "targetWeightPlaceholder": "155",
        "strengthDaysLabel": "Strength training days per week",
        "strengthDaysPlaceholder": "Select days",
        "ageLabel": "Age",
        "agePlaceholder": "48",
        "progressEnabled": true,
        "progressStepOneLabel": "Step 1 of 2: Quick Calculator",
        "progressStepOneText": "Answer 3 quick questions to calculate your personalized protein target immediately.",
        "progressStepTwoLabel": "Step 2 of 2: Send Your Plan",
        "progressStepTwoText": "Your custom plan is almost ready.",
        "targetPreviewStyle": "inline",
        "targetPreviewLabel": "Your Daily Target:",
        "quizButtonText": "Calculate",
        "leadHeadline": "Your Personalized Protein Plan Is Almost Ready",
        "leadSubheadline": "Just enter your name and email below. We'll send you access to your 7-day meal plan + grocery list instantly, then you’ll have 100% control to customize it with your dietary preferences on the next page.",
        "firstNameLabel": "First name",
        "firstNamePlaceholder": "First Name",
        "emailLabel": "Email",
        "emailPlaceholder": "Email",
        "leadButtonText": "Send My Free Personalized Protein Plan Now",
        "backButtonText": "Back"
      },
      "trackingVersion": "6/22/2026",
      "trackingFingerprint": "{\"headline\":\"Get Your Exact Daily Protein Target + Custom 7-Day Family Meal Plan (Free Grocery List Included)\",\"subheadline\":\"Takes 30 seconds. Backed by 1,000+ hours of Nutrition & Wellness Coaching. Built for busy parents. \",\"subheadlineHtml\":\"<span><span>Takes 30 seconds. <b>Backed by 1,000+ hours of Nutrition &amp; Wellness Coaching. </b></span></span><span>Built for busy parents. </span>\",\"buttonText\":\"Show My Protein Plan\",\"imageUrl\":\"https://res.cloudinary.com/dsvlnioq9/image/upload/v1782135119/protien_plan_calculate_preview_and_male_female_pomke9.png\",\"imageAlt\":\"\",\"width\":560,\"height\":560,\"sizeToImage\":true,\"backgroundColor\":\"#fbfaf7\",\"textColor\":\"#1c2520\",\"accentColor\":\"#06b00b\",\"fontFamily\":\"Arial, Helvetica, sans-serif\",\"textAlign\":\"center\",\"trafficSplit\":50,\"proteinQuiz\":{\"targetWeightLabel\":\"Target weight in lbs\",\"targetWeightPlaceholder\":\"155\",\"strengthDaysLabel\":\"Strength training days per week\",\"strengthDaysPlaceholder\":\"Select days\",\"ageLabel\":\"Age\",\"agePlaceholder\":\"48\",\"progressEnabled\":true,\"progressStepOneLabel\":\"Step 1 of 2: Quick Calculator\",\"progressStepOneText\":\"Answer 3 quick questions to calculate your personalized protein target immediately.\",\"progressStepTwoLabel\":\"Step 2 of 2: Send Your Plan\",\"progressStepTwoText\":\"Your custom plan is almost ready.\",\"targetPreviewStyle\":\"inline\",\"targetPreviewLabel\":\"Your Daily Target:\",\"quizButtonText\":\"Calculate\",\"leadHeadline\":\"Your Personalized Protein Plan Is Almost Ready\",\"leadSubheadline\":\"Just enter your name and email below. We'll send you access to your 7-day meal plan + grocery list instantly, then you’ll have 100% control to customize it with your dietary preferences on the next page.\",\"firstNameLabel\":\"First name\",\"firstNamePlaceholder\":\"First Name\",\"emailLabel\":\"Email\",\"emailPlaceholder\":\"Email\",\"leadButtonText\":\"Send My Free Personalized Protein Plan Now\",\"backButtonText\":\"Back\"}}"
    }
  ],
  "configVersion": "6/23/2026",
  "changeNote": "A - no people, just iphone app in hand mockup",
  "savedColors": [
    "#111827",
    "#ffffff",
    "#f8fafc",
    "#172026",
    "#1f6feb",
    "#0f766e",
    "#f0782e",
    "#fbfaf7",
    "#1c2520",
    "#d9dee7"
  ],
  "kajabiEmbedMode": "iframe",
  "formMode": "zapier",
  "leadWebhookUrl": "https://hooks.zapier.com/hooks/catch/18993655/4b2jb8t/",
  "leadMagnetMode": "protein_plan",
  "proteinPlanUrl": "https://www.longevitylifestyle.me/personalized-protein-plan",
  "proteinQuiz": {
    "targetWeightLabel": "Target weight in lbs",
    "targetWeightPlaceholder": "155",
    "strengthDaysLabel": "Strength training days",
    "strengthDaysPlaceholder": "Select days",
    "ageLabel": "Age",
    "agePlaceholder": "48",
    "progressEnabled": false,
    "progressStepOneLabel": "Step 1 of 2: Quick Calculator",
    "progressStepOneText": "Answer 3 quick questions to calculate your personalized protein target immediately.",
    "progressStepTwoLabel": "Step 2 of 2: Send Your Plan",
    "progressStepTwoText": "Your personalized target is ready. Tell us where to send the full plan.",
    "targetPreviewStyle": "off",
    "targetPreviewLabel": "Your Daily Target:",
    "quizButtonText": "Continue",
    "leadHeadline": "Get your free personalized protein goal + 7-day high-protein meal plan",
    "leadSubheadline": "Tell us where to send it, then your plan will open right away.",
    "firstNameLabel": "First name",
    "firstNamePlaceholder": "First Name",
    "emailLabel": "Email",
    "emailPlaceholder": "Email",
    "leadButtonText": "Show My Protein Plan",
    "backButtonText": "Back"
  },
  "draftSavedAt": "2026-06-23T19:55:14.509Z"
};
})();
