(function () {
  window.LL_POPUP_CONFIG = {
  "testId": "blog-optin-v1",
  "webhookUrl": "https://script.google.com/macros/s/AKfycbzZmjBOkq6JYxFEeMzemDozYiUOuAYZjkBAw5-0afFO_JLb1-riB9jeAIfWn40nlDqVnQ/exec",
  "kajabiFormEmbed": "<script src=https://www.longevitylifestyle.me/forms/2148823405/embed.js></script>",
  "cooldownDaysAfterClose": 7,
  "cooldownDaysAfterSubmitAttempt": 90,
  "assignmentDays": 30,
  "triggers": {
    "delayMs": 20000,
    "scrollDepth": 0
  },
  "variants": [
    {
      "id": "A",
      "name": "Control - Winning Variant",
      "active": true,
      "trafficSplit": 34,
      "headline": "Get Your High-Protein Week Planned in Seconds",
      "subheadline": "Simple meals, a personalized grocery list, and protein already calculated - so you can stay full without overthinking your meals.",
      "imageUrl": "https://res.cloudinary.com/dsvlnioq9/image/upload/v1782135119/protien_plan_calculate_preview_and_male_female_pomke9.png",
      "width": 810,
      "backgroundColor": "#fbfaf7",
      "textColor": "#1c2520",
      "accentColor": "#ea8011",
      "buttonText": "Show My Protein Plan",
      "fontFamily": "Arial, Helvetica, sans-serif",
      "imageAlt": "",
      "textAlign": "center",
      "height": 560,
      "sizeToImage": true,
      "subheadlineHtml": "Simple meals, a <b>personalized grocery list</b>, and <b>protein already calculated</b> - so you can <b>stay full without overthinking</b> your meals.",
      "proteinQuiz": {
        "targetWeightLabel": "Target weight in lbs",
        "targetWeightPlaceholder": "155",
        "strengthDaysLabel": "Strength training days per week",
        "strengthDaysPlaceholder": "Select days",
        "ageLabel": "Age",
        "agePlaceholder": "48",
        "multiStepEnabled": false,
        "targetWeightAnswerStyle": "dropdown",
        "strengthDaysAnswerStyle": "dropdown",
        "ageAnswerStyle": "dropdown",
        "progressEnabled": true,
        "progressStepOneLabel": "Step 1 of 2: Quick Calculator",
        "progressStepOneText": "Answer 3 quick questions to calculate your personalized protein target immediately.",
        "progressStepTwoLabel": "Step 2 of 2: Send Your Plan",
        "progressStepTwoText": "Your custom plan is almost ready.",
        "progressSingleStepLabel": "Step 1",
        "progressSingleStepLabelFontSize": "20",
        "targetPreviewStyle": "inline",
        "targetPreviewLabel": "Your Daily Target:",
        "showQuizStep": false,
        "showFirstName": false,
        "showEmail": true,
        "quizButtonText": "Calculate",
        "leadHeadline": "Get Your High-Protein Week Planned in Seconds",
        "leadSubheadline": "Simple meals, a personalized grocery list, and protein already calculated - so you can stay full without overthinking your meals.",
        "firstNameLabel": "First name",
        "firstNamePlaceholder": "First Name",
        "emailLabel": "Email",
        "emailPlaceholder": "Email",
        "leadButtonText": "Build My Free Plan",
        "backButtonText": "Back"
      },
      "trackingVersion": "7/25/2026 #2",
      "trackingFingerprint": "{\"headline\":\"Get Your High-Protein Week Planned in Seconds\",\"headlineHtml\":\"Get Your High-Protein Week Planned in Seconds\",\"headlineFontSize\":44,\"subheadline\":\"Simple meals, a personalized grocery list, and protein already calculated - so you can stay full without overthinking your meals.\",\"subheadlineHtml\":\"Simple meals, a <b>personalized grocery list</b>, and <b>protein already calculated</b> - so you can <b>stay full without overthinking</b> your meals.\",\"subheadlineFontSize\":26,\"valueLine\":\"Simple meals, daily protein target, and grocery list included.\",\"valueLineHtml\":\"<br>\",\"valueLineFontSize\":24,\"buttonText\":\"Show My Protein Plan\",\"buttonFontSize\":56,\"imageUrl\":\"https://res.cloudinary.com/dsvlnioq9/image/upload/v1782135119/protien_plan_calculate_preview_and_male_female_pomke9.png\",\"imageAlt\":\"\",\"width\":810,\"height\":560,\"sizeToImage\":true,\"backgroundColor\":\"#fbfaf7\",\"textColor\":\"#1c2520\",\"brandAccentColor\":\"#06b00b\",\"accentColor\":\"#ea8011\",\"fontFamily\":\"Arial, Helvetica, sans-serif\",\"headlineFontWeight\":700,\"bodyFontWeight\":400,\"buttonFontWeight\":700,\"textAlign\":\"center\",\"reminderEnabled\":true,\"reminderText\":\"Free Protein Plan\",\"reminderColor\":\"#ea8011\",\"reminderTextColor\":\"#ffffff\",\"reopenAfterCloseSeconds\":35,\"proteinQuiz\":{\"targetWeightLabel\":\"Target weight in lbs\",\"targetWeightPlaceholder\":\"155\",\"strengthDaysLabel\":\"Strength training days per week\",\"strengthDaysPlaceholder\":\"Select days\",\"ageLabel\":\"Age\",\"agePlaceholder\":\"48\",\"multiStepEnabled\":false,\"targetWeightAnswerStyle\":\"dropdown\",\"strengthDaysAnswerStyle\":\"dropdown\",\"ageAnswerStyle\":\"dropdown\",\"progressEnabled\":true,\"progressStepOneLabel\":\"Step 1 of 2: Quick Calculator\",\"progressStepOneText\":\"Answer 3 quick questions to calculate your personalized protein target immediately.\",\"progressStepTwoLabel\":\"Step 2 of 2: Send Your Plan\",\"progressStepTwoText\":\"Your custom plan is almost ready.\",\"progressSingleStepLabel\":\"Step 1\",\"progressSingleStepLabelFontSize\":\"20\",\"targetPreviewStyle\":\"inline\",\"targetPreviewLabel\":\"Your Daily Target:\",\"showQuizStep\":false,\"showFirstName\":false,\"showEmail\":true,\"quizButtonText\":\"Calculate\",\"leadHeadline\":\"Get Your High-Protein Week Planned in Seconds\",\"leadSubheadline\":\"Simple meals, a personalized grocery list, and protein already calculated - so you can stay full without overthinking your meals.\",\"firstNameLabel\":\"First name\",\"firstNamePlaceholder\":\"First Name\",\"emailLabel\":\"Email\",\"emailPlaceholder\":\"Email\",\"leadButtonText\":\"Build My Free Plan\",\"backButtonText\":\"Back\"},\"flowSteps\":[{\"headlineHtml\":\"Get Your High-Protein Week Planned in Seconds\",\"subheadlineHtml\":\"Simple meals, a <b>personalized grocery list</b>, and <b>protein already calculated</b> - so you can <b>stay full without overthinking</b> your meals.\",\"valueLineHtml\":\"<br>\",\"imageUrl\":\"https://res.cloudinary.com/dsvlnioq9/image/upload/v1782135119/protien_plan_calculate_preview_and_male_female_pomke9.png\",\"id\":\"step_2b3tu6\",\"name\":\"Lead Form\",\"type\":\"lead\",\"enabled\":true,\"fields\":[\"email\"],\"firstNameLabel\":\"First name\",\"firstNamePlaceholder\":\"First Name\",\"emailLabel\":\"Email\",\"emailPlaceholder\":\"Email\",\"buttonText\":\"Build My Free Plan\",\"progressEnabled\":true,\"progressLabel\":\"Step 1\",\"targetPreviewStyle\":\"off\",\"targetPreviewLabel\":\"Your Daily Target:\",\"showFirstName\":false,\"showEmail\":true,\"eyebrowColor\":\"#6b7280\"}]}",
      "valueLine": "Simple meals, daily protein target, and grocery list included.",
      "headlineHtml": "Get Your High-Protein Week Planned in Seconds",
      "headlineFontSize": 44,
      "subheadlineFontSize": 26,
      "valueLineHtml": "<br>",
      "valueLineFontSize": 24,
      "buttonFontSize": 56,
      "brandAccentColor": "#06b00b",
      "flowSteps": [
        {
          "headlineHtml": "Get Your High-Protein Week Planned in Seconds",
          "subheadlineHtml": "Simple meals, a <b>personalized grocery list</b>, and <b>protein already calculated</b> - so you can <b>stay full without overthinking</b> your meals.",
          "valueLineHtml": "<br>",
          "imageUrl": "https://res.cloudinary.com/dsvlnioq9/image/upload/v1782135119/protien_plan_calculate_preview_and_male_female_pomke9.png",
          "id": "step_2b3tu6",
          "name": "Lead Form",
          "type": "lead",
          "enabled": true,
          "fields": [
            "email"
          ],
          "firstNameLabel": "First name",
          "firstNamePlaceholder": "First Name",
          "emailLabel": "Email",
          "emailPlaceholder": "Email",
          "buttonText": "Build My Free Plan",
          "progressEnabled": true,
          "progressLabel": "Step 1",
          "targetPreviewStyle": "off",
          "targetPreviewLabel": "Your Daily Target:",
          "showFirstName": false,
          "showEmail": true,
          "eyebrowColor": "#6b7280"
        }
      ],
      "headlineFontWeight": 700,
      "bodyFontWeight": 400,
      "buttonFontWeight": 700,
      "eyebrowColor": "#6b7280",
      "reminderEnabled": true,
      "reminderText": "Free Protein Plan",
      "reminderColor": "#ea8011",
      "reopenAfterCloseSeconds": 35,
      "reminderTextColor": "#ffffff",
      "trackingSources": [
        {
          "variant": "C",
          "configVersion": "7/25/2026 #2"
        }
      ],
      "trackingLabel": "Planned In Seconds",
      "trackingStartedAt": "2026-07-26T00:43:22.521Z"
    },
    {
      "id": "B",
      "name": "Headline Challenger - Stay Fuller",
      "active": true,
      "trafficSplit": 33,
      "headline": "Get Your High-Protein Week Planned in Seconds",
      "subheadline": "Simple meals, a personalized grocery list, and protein already calculated - so you can stay full without overthinking your meals.",
      "imageUrl": "https://ajpanella.github.io/kajabi-popup-ab-tool/popup/assets/uploads/same-image-new-mockup-34f5b82f1eaa.png",
      "width": 810,
      "backgroundColor": "#fbfaf7",
      "textColor": "#1c2520",
      "accentColor": "#ea8011",
      "buttonText": "Show My Protein Plan",
      "fontFamily": "Arial, Helvetica, sans-serif",
      "imageAlt": "",
      "textAlign": "center",
      "height": 560,
      "sizeToImage": true,
      "subheadlineHtml": "<span>Simple meals, a </span><b>personalized grocery list</b><span>, and </span><b>protein already calculated</b><span> - so you can </span><b>stay full without overthinking</b><span> your meals.</span>",
      "proteinQuiz": {
        "targetWeightLabel": "Target weight in lbs",
        "targetWeightPlaceholder": "155",
        "strengthDaysLabel": "Strength training days per week",
        "strengthDaysPlaceholder": "Select days",
        "ageLabel": "Age",
        "agePlaceholder": "48",
        "multiStepEnabled": false,
        "targetWeightAnswerStyle": "dropdown",
        "strengthDaysAnswerStyle": "dropdown",
        "ageAnswerStyle": "dropdown",
        "progressEnabled": true,
        "progressStepOneLabel": "Step 1 of 2: Quick Calculator",
        "progressStepOneText": "Answer 3 quick questions to calculate your personalized protein target immediately.",
        "progressStepTwoLabel": "Step 2 of 2: Send Your Plan",
        "progressStepTwoText": "Your custom plan is almost ready.",
        "progressSingleStepLabel": "Step 1",
        "progressSingleStepLabelFontSize": "20",
        "targetPreviewStyle": "inline",
        "targetPreviewLabel": "Your Daily Target:",
        "showQuizStep": false,
        "showFirstName": false,
        "showEmail": true,
        "quizButtonText": "Calculate",
        "leadHeadline": "Get Your High-Protein Week Planned in Seconds",
        "leadSubheadline": "Simple meals, a personalized grocery list, and protein already calculated - so you can stay full without overthinking your meals.",
        "firstNameLabel": "First name",
        "firstNamePlaceholder": "First Name",
        "emailLabel": "Email",
        "emailPlaceholder": "Email",
        "leadButtonText": "Build My Free Plan",
        "backButtonText": "Back"
      },
      "trackingVersion": "8/4/2026 · get-your-high-protein-week-p-vlay",
      "trackingFingerprint": "{\"headline\":\"Get Your High-Protein Week Planned in Seconds\",\"headlineHtml\":\"<span>Get Your High-Protein Week Planned in Seconds</span>\",\"headlineFontSize\":44,\"subheadline\":\"Simple meals, a personalized grocery list, and protein already calculated - so you can stay full without overthinking your meals.\",\"subheadlineHtml\":\"<span>Simple meals, a </span><b>personalized grocery list</b><span>, and </span><b>protein already calculated</b><span> - so you can </span><b>stay full without overthinking</b><span> your meals.</span>\",\"subheadlineFontSize\":26,\"valueLine\":\"Simple meals, daily protein target, and grocery list included.\",\"valueLineHtml\":\"<br>\",\"valueLineFontSize\":24,\"buttonText\":\"Show My Protein Plan\",\"buttonFontSize\":56,\"imageUrl\":\"https://ajpanella.github.io/kajabi-popup-ab-tool/popup/assets/uploads/same-image-new-mockup-34f5b82f1eaa.png\",\"imageAlt\":\"\",\"width\":810,\"height\":560,\"sizeToImage\":true,\"backgroundColor\":\"#fbfaf7\",\"textColor\":\"#1c2520\",\"brandAccentColor\":\"#06b00b\",\"accentColor\":\"#ea8011\",\"fontFamily\":\"Arial, Helvetica, sans-serif\",\"headlineFontWeight\":700,\"bodyFontWeight\":400,\"buttonFontWeight\":700,\"textAlign\":\"center\",\"reminderEnabled\":true,\"reminderText\":\"Free Protein Plan\",\"reminderColor\":\"#ea8011\",\"reminderTextColor\":\"#ffffff\",\"reopenAfterCloseSeconds\":35,\"proteinQuiz\":{\"targetWeightLabel\":\"Target weight in lbs\",\"targetWeightPlaceholder\":\"155\",\"strengthDaysLabel\":\"Strength training days per week\",\"strengthDaysPlaceholder\":\"Select days\",\"ageLabel\":\"Age\",\"agePlaceholder\":\"48\",\"multiStepEnabled\":false,\"targetWeightAnswerStyle\":\"dropdown\",\"strengthDaysAnswerStyle\":\"dropdown\",\"ageAnswerStyle\":\"dropdown\",\"progressEnabled\":true,\"progressStepOneLabel\":\"Step 1 of 2: Quick Calculator\",\"progressStepOneText\":\"Answer 3 quick questions to calculate your personalized protein target immediately.\",\"progressStepTwoLabel\":\"Step 2 of 2: Send Your Plan\",\"progressStepTwoText\":\"Your custom plan is almost ready.\",\"progressSingleStepLabel\":\"Step 1\",\"progressSingleStepLabelFontSize\":\"20\",\"targetPreviewStyle\":\"inline\",\"targetPreviewLabel\":\"Your Daily Target:\",\"showQuizStep\":false,\"showFirstName\":false,\"showEmail\":true,\"quizButtonText\":\"Calculate\",\"leadHeadline\":\"Get Your High-Protein Week Planned in Seconds\",\"leadSubheadline\":\"Simple meals, a personalized grocery list, and protein already calculated - so you can stay full without overthinking your meals.\",\"firstNameLabel\":\"First name\",\"firstNamePlaceholder\":\"First Name\",\"emailLabel\":\"Email\",\"emailPlaceholder\":\"Email\",\"leadButtonText\":\"Build My Free Plan\",\"backButtonText\":\"Back\"},\"flowSteps\":[{\"headlineHtml\":\"<span>Get Your High-Protein Week Planned in Seconds</span>\",\"subheadlineHtml\":\"<span>Simple meals, a </span><b>personalized grocery list</b><span>, and </span><b>protein already calculated</b><span> - so you can </span><b>stay full without overthinking</b><span> your meals.</span>\",\"valueLineHtml\":\"<br>\",\"imageUrl\":\"https://ajpanella.github.io/kajabi-popup-ab-tool/popup/assets/uploads/same-image-new-mockup-34f5b82f1eaa.png\",\"id\":\"step_2b3tu6\",\"name\":\"Lead Form\",\"type\":\"lead\",\"enabled\":true,\"fields\":[\"email\"],\"firstNameLabel\":\"First name\",\"firstNamePlaceholder\":\"First Name\",\"emailLabel\":\"Email\",\"emailPlaceholder\":\"Email\",\"buttonText\":\"Build My Free Plan\",\"progressEnabled\":true,\"progressLabel\":\"Step 1\",\"targetPreviewStyle\":\"off\",\"targetPreviewLabel\":\"Your Daily Target:\",\"showFirstName\":false,\"showEmail\":true,\"eyebrowColor\":\"#6b7280\"}]}",
      "valueLine": "Simple meals, daily protein target, and grocery list included.",
      "headlineHtml": "<span>Get Your High-Protein Week Planned in Seconds</span>",
      "headlineFontSize": 44,
      "subheadlineFontSize": 26,
      "valueLineHtml": "<br>",
      "valueLineFontSize": 24,
      "buttonFontSize": 56,
      "brandAccentColor": "#06b00b",
      "flowSteps": [
        {
          "headlineHtml": "<span>Get Your High-Protein Week Planned in Seconds</span>",
          "subheadlineHtml": "<span>Simple meals, a </span><b>personalized grocery list</b><span>, and </span><b>protein already calculated</b><span> - so you can </span><b>stay full without overthinking</b><span> your meals.</span>",
          "valueLineHtml": "<br>",
          "imageUrl": "https://ajpanella.github.io/kajabi-popup-ab-tool/popup/assets/uploads/same-image-new-mockup-34f5b82f1eaa.png",
          "id": "step_2b3tu6",
          "name": "Lead Form",
          "type": "lead",
          "enabled": true,
          "fields": [
            "email"
          ],
          "firstNameLabel": "First name",
          "firstNamePlaceholder": "First Name",
          "emailLabel": "Email",
          "emailPlaceholder": "Email",
          "buttonText": "Build My Free Plan",
          "progressEnabled": true,
          "progressLabel": "Step 1",
          "targetPreviewStyle": "off",
          "targetPreviewLabel": "Your Daily Target:",
          "showFirstName": false,
          "showEmail": true,
          "eyebrowColor": "#6b7280"
        }
      ],
      "headlineFontWeight": 700,
      "bodyFontWeight": 400,
      "buttonFontWeight": 700,
      "eyebrowColor": "#6b7280",
      "reminderEnabled": true,
      "reminderText": "Free Protein Plan",
      "reminderColor": "#ea8011",
      "reopenAfterCloseSeconds": 35,
      "reminderTextColor": "#ffffff",
      "trackingSources": [],
      "trackingLabel": "Planned In Seconds · VLAY",
      "trackingStartedAt": "2026-08-04T15:24:59.002Z"
    },
    {
      "id": "C",
      "name": "Headline Challenger - In 30 Seconds",
      "active": true,
      "trafficSplit": 33,
      "headline": "Get Your High-Protein Week Planned in Seconds",
      "subheadline": "Simple customizable meals, a printable grocery list, with protein already calculated - so you can stay full without overthinking it.",
      "imageUrl": "https://ajpanella.github.io/kajabi-popup-ab-tool/popup/assets/uploads/same-image-new-mockup-34f5b82f1eaa.png",
      "width": 810,
      "backgroundColor": "#fbfaf7",
      "textColor": "#1c2520",
      "accentColor": "#ea8011",
      "buttonText": "Show My Protein Plan",
      "fontFamily": "Arial, Helvetica, sans-serif",
      "imageAlt": "",
      "textAlign": "center",
      "height": 560,
      "sizeToImage": true,
      "subheadlineHtml": "<span>Simple&nbsp;</span><b>customizable meals, </b>a printable<b> grocery list</b><span>, with&nbsp;</span><b>protein already calculated</b><span> - so you can </span><b>stay full without overthinking</b><span> <b>it.</b></span>",
      "proteinQuiz": {
        "targetWeightLabel": "Target weight in lbs",
        "targetWeightPlaceholder": "155",
        "strengthDaysLabel": "Strength training days per week",
        "strengthDaysPlaceholder": "Select days",
        "ageLabel": "Age",
        "agePlaceholder": "48",
        "multiStepEnabled": false,
        "targetWeightAnswerStyle": "dropdown",
        "strengthDaysAnswerStyle": "dropdown",
        "ageAnswerStyle": "dropdown",
        "progressEnabled": true,
        "progressStepOneLabel": "Step 1 of 2: Quick Calculator",
        "progressStepOneText": "Answer 3 quick questions to calculate your personalized protein target immediately.",
        "progressStepTwoLabel": "Step 2 of 2: Send Your Plan",
        "progressStepTwoText": "Your custom plan is almost ready.",
        "progressSingleStepLabel": "Step 1",
        "progressSingleStepLabelFontSize": "20",
        "targetPreviewStyle": "inline",
        "targetPreviewLabel": "Your Daily Target:",
        "showQuizStep": false,
        "showFirstName": false,
        "showEmail": true,
        "quizButtonText": "Calculate",
        "leadHeadline": "Get Your High-Protein Week Planned in Seconds",
        "leadSubheadline": "Simple customizable meals, a printable grocery list, with protein already calculated - so you can stay full without overthinking it.",
        "firstNameLabel": "First name",
        "firstNamePlaceholder": "First Name",
        "emailLabel": "Email",
        "emailPlaceholder": "Email",
        "leadButtonText": "Build My Free Plan",
        "backButtonText": "Back"
      },
      "trackingVersion": "8/4/2026 · get-your-high-protein-week-p-w3l2",
      "trackingFingerprint": "{\"headline\":\"Get Your High-Protein Week Planned in Seconds\",\"headlineHtml\":\"Get Your High-Protein Week Planned in Seconds\",\"headlineFontSize\":44,\"subheadline\":\"Simple customizable meals, a printable grocery list, with protein already calculated - so you can stay full without overthinking it.\",\"subheadlineHtml\":\"<span>Simple&nbsp;</span><b>customizable meals, </b>a printable<b> grocery list</b><span>, with&nbsp;</span><b>protein already calculated</b><span> - so you can </span><b>stay full without overthinking</b><span> <b>it.</b></span>\",\"subheadlineFontSize\":26,\"valueLine\":\"Simple meals, daily protein target, and grocery list included.\",\"valueLineHtml\":\"<br>\",\"valueLineFontSize\":24,\"buttonText\":\"Show My Protein Plan\",\"buttonFontSize\":56,\"imageUrl\":\"https://ajpanella.github.io/kajabi-popup-ab-tool/popup/assets/uploads/same-image-new-mockup-34f5b82f1eaa.png\",\"imageAlt\":\"\",\"width\":810,\"height\":560,\"sizeToImage\":true,\"backgroundColor\":\"#fbfaf7\",\"textColor\":\"#1c2520\",\"brandAccentColor\":\"#06b00b\",\"accentColor\":\"#ea8011\",\"fontFamily\":\"Arial, Helvetica, sans-serif\",\"headlineFontWeight\":700,\"bodyFontWeight\":400,\"buttonFontWeight\":700,\"textAlign\":\"center\",\"reminderEnabled\":true,\"reminderText\":\"Free Protein Plan\",\"reminderColor\":\"#ea8011\",\"reminderTextColor\":\"#ffffff\",\"reopenAfterCloseSeconds\":35,\"proteinQuiz\":{\"targetWeightLabel\":\"Target weight in lbs\",\"targetWeightPlaceholder\":\"155\",\"strengthDaysLabel\":\"Strength training days per week\",\"strengthDaysPlaceholder\":\"Select days\",\"ageLabel\":\"Age\",\"agePlaceholder\":\"48\",\"multiStepEnabled\":false,\"targetWeightAnswerStyle\":\"dropdown\",\"strengthDaysAnswerStyle\":\"dropdown\",\"ageAnswerStyle\":\"dropdown\",\"progressEnabled\":true,\"progressStepOneLabel\":\"Step 1 of 2: Quick Calculator\",\"progressStepOneText\":\"Answer 3 quick questions to calculate your personalized protein target immediately.\",\"progressStepTwoLabel\":\"Step 2 of 2: Send Your Plan\",\"progressStepTwoText\":\"Your custom plan is almost ready.\",\"progressSingleStepLabel\":\"Step 1\",\"progressSingleStepLabelFontSize\":\"20\",\"targetPreviewStyle\":\"inline\",\"targetPreviewLabel\":\"Your Daily Target:\",\"showQuizStep\":false,\"showFirstName\":false,\"showEmail\":true,\"quizButtonText\":\"Calculate\",\"leadHeadline\":\"Get Your High-Protein Week Planned in Seconds\",\"leadSubheadline\":\"Simple customizable meals, a printable grocery list, with protein already calculated - so you can stay full without overthinking it.\",\"firstNameLabel\":\"First name\",\"firstNamePlaceholder\":\"First Name\",\"emailLabel\":\"Email\",\"emailPlaceholder\":\"Email\",\"leadButtonText\":\"Build My Free Plan\",\"backButtonText\":\"Back\"},\"flowSteps\":[{\"headlineHtml\":\"Get Your High-Protein Week Planned in Seconds\",\"subheadlineHtml\":\"<span>Simple&nbsp;</span><b>customizable meals, </b>a printable<b> grocery list</b><span>, with&nbsp;</span><b>protein already calculated</b><span> - so you can </span><b>stay full without overthinking</b><span> <b>it.</b></span>\",\"valueLineHtml\":\"<br>\",\"imageUrl\":\"https://ajpanella.github.io/kajabi-popup-ab-tool/popup/assets/uploads/same-image-new-mockup-34f5b82f1eaa.png\",\"id\":\"step_2b3tu6\",\"name\":\"Lead Form\",\"type\":\"lead\",\"enabled\":true,\"fields\":[\"email\"],\"firstNameLabel\":\"First name\",\"firstNamePlaceholder\":\"First Name\",\"emailLabel\":\"Email\",\"emailPlaceholder\":\"Email\",\"buttonText\":\"Build My Free Plan\",\"progressEnabled\":true,\"progressLabel\":\"Step 1\",\"targetPreviewStyle\":\"off\",\"targetPreviewLabel\":\"Your Daily Target:\",\"showFirstName\":false,\"showEmail\":true,\"eyebrowColor\":\"#6b7280\"}]}",
      "valueLine": "Simple meals, daily protein target, and grocery list included.",
      "headlineHtml": "Get Your High-Protein Week Planned in Seconds",
      "headlineFontSize": 44,
      "subheadlineFontSize": 26,
      "valueLineHtml": "<br>",
      "valueLineFontSize": 24,
      "buttonFontSize": 56,
      "brandAccentColor": "#06b00b",
      "flowSteps": [
        {
          "headlineHtml": "Get Your High-Protein Week Planned in Seconds",
          "subheadlineHtml": "<span>Simple&nbsp;</span><b>customizable meals, </b>a printable<b> grocery list</b><span>, with&nbsp;</span><b>protein already calculated</b><span> - so you can </span><b>stay full without overthinking</b><span> <b>it.</b></span>",
          "valueLineHtml": "<br>",
          "imageUrl": "https://ajpanella.github.io/kajabi-popup-ab-tool/popup/assets/uploads/same-image-new-mockup-34f5b82f1eaa.png",
          "id": "step_2b3tu6",
          "name": "Lead Form",
          "type": "lead",
          "enabled": true,
          "fields": [
            "email"
          ],
          "firstNameLabel": "First name",
          "firstNamePlaceholder": "First Name",
          "emailLabel": "Email",
          "emailPlaceholder": "Email",
          "buttonText": "Build My Free Plan",
          "progressEnabled": true,
          "progressLabel": "Step 1",
          "targetPreviewStyle": "off",
          "targetPreviewLabel": "Your Daily Target:",
          "showFirstName": false,
          "showEmail": true,
          "eyebrowColor": "#6b7280"
        }
      ],
      "headlineFontWeight": 700,
      "bodyFontWeight": 400,
      "buttonFontWeight": 700,
      "eyebrowColor": "#6b7280",
      "reminderEnabled": true,
      "reminderText": "Free Protein Plan",
      "reminderColor": "#ea8011",
      "reopenAfterCloseSeconds": 35,
      "reminderTextColor": "#ffffff",
      "trackingSources": [],
      "trackingLabel": "Planned In Seconds · W3L2",
      "trackingStartedAt": "2026-08-04T15:24:59.002Z"
    }
  ],
  "configVersion": "8/4/2026",
  "dashboardDraftResetToken": "2026-07-29-control-c-promoted-to-a",
  "changeNote": "Promoted unchanged winning control from C to A; retained Stay Fuller in B and moved In 30 Seconds to C",
  "savedColors": [
    "#07b00c",
    "#ea8011",
    "#fcfcfc",
    "#050505",
    "#1f6feb",
    "#0f766e",
    "#f0782e",
    "#fbfaf7",
    "#1c2520",
    "#d9dee7"
  ],
  "kajabiEmbedMode": "iframe",
  "formMode": "zapier",
  "leadWebhookUrl": "https://hooks.zapier.com/hooks/catch/18993655/4b2jb8t/",
  "leadMagnetMode": "protein_plan",
  "proteinPlanUrl": "https://www.longevitylifestyle.me/personalized-protein-plan",
  "proteinQuiz": {
    "targetWeightLabel": "Target weight in lbs",
    "targetWeightPlaceholder": "155",
    "strengthDaysLabel": "Strength training days",
    "strengthDaysPlaceholder": "Select days",
    "ageLabel": "Age",
    "agePlaceholder": "48",
    "multiStepEnabled": false,
    "targetWeightAnswerStyle": "dropdown",
    "strengthDaysAnswerStyle": "dropdown",
    "ageAnswerStyle": "dropdown",
    "progressEnabled": false,
    "progressStepOneLabel": "Step 1 of 2: Quick Calculator",
    "progressStepOneText": "Answer 3 quick questions to calculate your personalized protein target immediately.",
    "progressStepTwoLabel": "Step 2 of 2: Send Your Plan",
    "progressStepTwoText": "Your personalized target is ready. Tell us where to send the full plan.",
    "progressSingleStepLabel": "Step 1",
    "progressSingleStepLabelFontSize": "",
    "targetPreviewStyle": "off",
    "targetPreviewLabel": "Your Daily Target:",
    "showQuizStep": true,
    "showFirstName": true,
    "showEmail": true,
    "quizButtonText": "Continue",
    "leadHeadline": "Get your free personalized protein goal + 7-day high-protein meal plan",
    "leadSubheadline": "Tell us where to send it, then your plan will open right away.",
    "firstNameLabel": "First name",
    "firstNamePlaceholder": "First Name",
    "emailLabel": "Email",
    "emailPlaceholder": "Email",
    "leadButtonText": "Show My Protein Plan",
    "backButtonText": "Back"
  },
  "draftSavedAt": "2026-08-04T15:24:59.018Z",
  "reopenAfterCloseSeconds": 35,
  "trackingCsvUrl": "https://docs.google.com/spreadsheets/d/e/2PACX-1vTL2htdRxc9IM_ok_bTcrYPMccocLdF0I8_yNIZRkkRp3a23yCQDA4gBuWzByWQNGLVxtniZJvAAlAY/pub?output=csv",
  "publishedAt": "2026-08-04T15:24:59.002Z",
  "publishId": "publish-20260804152459"
};
})();
